mailgun.settings:
  type: config_object
  label: 'Mailgun settings'
  mapping:
    api_key:
      type: string
    api_endpoint:
      type: string
    api_working_domain:
      type: string
    debug_mode:
      type: boolean
